### ISSUE TITLE
Move out of Obsidian Publish

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/handbook#7]
I'm using less and less Obsidian and relying more on VS Code. I should move out of Obsidian Publish!

**Comment by davidgasquez** [comment]
Perhaps use https://eleventy-notes.sandroroth.com/?

**Comment by davidgasquez** [comment]
Or even rely on https://github.com/zoni/obsidian-export and then build it with anything.

**Comment by davidgasquez** [comment]
Got it working with `mdbook` with this config: 

```toml
[book]
authors = ["David Gasquez"]
language = "en"
multilingual = false
src = "."
title = "Handbook"

[build]
create-missing = false

[preprocessor.wikilinks]
command = "mdbook-wikilinks"

# [preprocessor.all-the-markdowns]
# draft-folders = true
#
# [[preprocessor.all-the-markdowns.section]]
# title = "Handbook"
# base = "."
# ignore = [ ]

[output.html]
git-repository-url = "https://github.com/davidgasquez/handbook"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"

no-section-label = false

#use as mdbook preprocessor
# [preprocessor.auto-gen-summary]
# first-line-as-link-text = true # indicate mdbook to make the first line(default the file name) of markdown file as the link text in SUMMARY.md

[output.html.fold]
enable = true
level = 0
```

Not the most ergonomic thing, but worth considering.
